---
- name: Scan for Java JDKs/JREs and generate a report
  hosts: all

  tasks:
    - name: Include Variables
      include_vars: vars/main.yaml

    - name: Create temp directory structure
      ansible.windows.win_file:
        path: C:\Temp\
        state: directory

    - name: Create temp directory structure
      ansible.windows.win_file:
        path: "C:\\Temp\\javaReport-{{ ansible_date_time.epoch }}"
        state: directory

    - name: Copy listPackages.ps1 to host
      ansible.windows.win_copy:
        src: files/listPackages.ps1
        dest: "C:\\Temp\\javaReport-{{ ansible_date_time.epoch }}\\listPackages.ps1"

    - name: Pull list of installed packages
      ansible.windows.win_shell: "C:\\Temp\\javaReport-{{ ansible_date_time.epoch }}\\listPackages.ps1"
      args:
        chdir: "C:\\Temp\\javaReport-{{ ansible_date_time.epoch }}\\"
      register: installed_products

    - name: Slurp up the JSON
      slurp:
        src: "C:\\Temp\\javaReport-{{ ansible_date_time.epoch }}\\detectedJava.json"
      register: detected_java

    - name: Debug
      debug:
        msg: "{{ detected_java['content'] | b64decode }}"
      tags:
        - never
        - debug

    - name: Template out the HTML report
      template:
        src: java_consumption_report.html.j2
        dest: "C:\\Temp\\javaReport-{{ ansible_date_time.epoch }}\\java_consumption_report-{{ ansible_date_time.epoch }}.html"
